db_name: ppi.db

dir:
  download: ./IMAGES/DOWNLOAD
  backup: ./IMAGES/BACKUP
  crop: ./IMAGES/CROP

allowed_processes:
  - ALBUMEN_PRINT
  - AMBROTYPE_TINTYPE_FERROTYPE
  - CARBON_PRINT
  - CYANOTYPE
  - DAGUERREOTYPE
  - DOP
  - POP
  - PLATINOTYPE_PALLADIOTYPE
  - SALTED_PAPER_PRINT
