db_name: ppi.db
dir:
  download: <REPLACE ME!>\IMAGES\DOWNLOAD
  backup: <REPLACE ME!>
  crop: <REPLACE ME!>\IMAGES\CROP
  classify: <REPLACE ME!>\IMAGES\CLASSIFY
allowed_processes:
  - ALBUMEN_PRINT
  - AMBROTYPE_TINTYPE_FERROTYPE
  - CARBON_PRINT
  - CYANOTYPE
  - DAGUERREOTYPE
  - DOP
  - POP
  - PLATINOTYPE_PALLADIOTYPE
  - SALTED_PAPER_PRINT